apiVersion: apps/v1
kind: Deployment
metadata:
  name: eccom-deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      app: eccom
  template:
    metadata:
      labels:
        app: eccom
    spec:
      containers:
      - name: eccom
        image: 636706114596.dkr.ecr.ap-south-1.amazonaws.com/ecomm-repo:latest
        ports:
        - containerPort: 8080

