apiVersion: v1
kind: Service
metadata:
  name: eccom-service
  labels:
    app: eccom          
spec:
  type: LoadBalancer
  selector:
    app: eccom         
  ports:
  - name: http           
    port: 80
    targetPort: 8080
